### ISSUE TITLE
Add sound to notification

### ISSUE THREAD

**Issue by RLP1369** [Aohzan/hass-blueprints#13]
Is there anyway to add a sound to the notification?  Ive tried to add through the optional actions, but without success.

Thank you in advance

**Comment by Aohzan** [comment]
It depends of your device type and of what you want to do : https://companion.home-assistant.io/docs/notifications/notification-sounds/
so edit the blueprint to what you want

**Comment by RLP1369** [comment]
I’m using iOS.  I have plenty of notifications that have sound, but I have not been successful in adding a sound to the blueprint.
Are you suggesting that the Optional Action should work?  If so, it breaks the entire blueprint. 
if you’re suggesting to add the appropriate code, which line of the blueprint should it be added?….because I’ve tried everything I can think of.

thank you.

**Comment by Aohzan** [comment]
it's a normal notify call : https://github.com/Aohzan/hass-blueprints/blob/main/blueprints/medication_reminder_ios.yaml#L175
you can try it on dev tools

**Comment by RLP1369** [comment]
Hello again,Ive tried everything under the sun to add a Home Assistant preloaded sound to the notification…all without success.If you’ve been able to do so, would you please share the code?Thank youSent from my iPadOn Aug 13, 2024, at 9:06 AM, Matthieu Bourgain ***@***.***> wrote:﻿
it's a normal notify call : https://github.com/Aohzan/hass-blueprints/blob/main/blueprints/medication_reminder_ios.yaml#L175
you can try it on dev tools

**Comment by Aohzan** [comment]
show me what you tried in dev tools
